---
version: "2.1"
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - libreoffice:/config
    ports:
      - 3010:3000
      - 3011:3001
    restart: unless-stopped

volumes:
  libreoffice:
    name: libreoffice
    
networks:
  default:
    external:
      name: Apps-Network
