services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: Code-Sserver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}
    volumes:
      - config:/config
    ports:
      - 2443:8443
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network
volumes:
  config: