services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Athens'
    # Volumes store your data between container upgrades
    volumes:
      - '/opt/appdata/wallos/db:/var/www/html/db'
      - '/opt/appdata/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
networks:
  default:
    external: true
    name: Apps-Network
