---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name:DuckDNS
    network_mode: host #optional
    environment:
      - PUID=${PUID} #optional
      - PGID=${PGID} #optional
      - TZ=${TZ} #optional
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4 #optional
      - LOG_FILE=false #optional
    volumes:
      - duckdns:/config #optional
    restart: unless-stopped

volumes:
  duckdns:
    name: duckdns
    external: true

networks:
  default:
      name: nextcloud
