services:
  postgres:
    image: postgres:15
    container_name: n8n_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRESDB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - TZ=${TZ}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - NODE_ENV=${NODE_ENV}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
    volumes:
      - app:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    entrypoint: /bin/sh -c "apk add docker-cli && n8n"
    depends_on:
      - cloudflared
      - postgres
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: N8N_domain
    restart: always
    command: tunnel --no-autoupdate run --token ${TOKEN}
   

networks:
  default:
    external: true
    name: Apps-Network

volumes:
  app:
  db: