services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - /opt/appdata/n8n:/home/node/.n8n
    restart: unless-stopped
    environment:
      - TZ=${TZ}  # Adjust if you're in a different timezone
      # Optional security and config settings:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
#      - N8N_SECURE_COOKIE=false
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: N8N_domain
    restart: always
    command: tunnel --no-autoupdate run --token ${TOKEN}
   

networks:
  default:
    external: true
    name: Apps-Network