---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: Duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS=${CLI_ARGS} #optional
    volumes:
      - /opt/appdata/duplicati/config:/config
      - ${backups}:/backups
      - ${source}:/source
    ports:
      - 8200:8200
    restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
