version: '3.3'
services:
    cloudflared:
        container_name: 'Office-Tunnel'
        image: 'cloudflare/cloudflared:latest'
        command: 'tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}'
        restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
