services:
    scrypted:
        volumes:
            - config:/server/volume
        container_name: scrypted
        restart: unless-stopped
        image: koush/scrypted
        ports:
            - 10443:8080
networks:
  default:
    external: true
    name: Apps-Network

volumes:
  config: