#version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: Prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/appdata/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/appdata/prometheus/data:/prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: Grafana
    ports:
      - "3000:3000"
    volumes:
      - /opt/appdata/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network  # External network configuration named Apps-Network

#sudo chown -R 65534:65534 /opt/appdata/prometheus/data

#sudo chown -R 472:472 /opt/appdata/grafana


