services:
  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot:latest
    container_name: rSnapshot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
      - /home/funmicra/rsnapshot:/.snapshots #optional
      - /home/funmicra:/data #optional
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network

volumes:
  config: