services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: Netboot.xyz
    environment:
      - MENU_VERSION=2.0.47 # optional
    volumes:
      - config:/config # optional
      - assets:/assets # optional
    ports:
      - 3002:3000
      - 69:69/udp
      - 8083:80 #optional
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network

volumes:
  config:
  assets:
