---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: Netboot.xyz
    environment:
      - MENU_VERSION=2.0.47 # optional
    volumes:
      - /opt/appdata/netbootxyz/config:/config # optional
      - /opt/appdata/netbootxyz/assets:/assets # optional
    ports:
      - 3002:3000
      - 69:69/udp
      - 8081:80 #optional
    restart: unless-stopped

networks:
  default:
    external:
      name: Apps-Network
