services:
  cloudflared:
    container_name: Nextcloud-Tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network
