services:
    agent:
        ports:
            - 9001:9001
        container_name: Portainer-Agent
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/volumes:/var/lib/docker/volumes
            - /:/host
        image: portainer/agent:2.33.3

networks:
  default:
    external: true
    name: Apps-Network
