version: '3.3'
services:
    agent:
        ports:
            - '9001:9001'
        container_name: Portainer-Agent
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/opt/appdata:/var/lib/docker/volumes'
        image: 'portainer/agent:2.19.1'

networks:
  default:
    name: Apps-Network
