services:
  matomo:
    image: matomo:latest
    container_name: matomo
    restart: always
    ports:
      - "8089:80"
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysqli
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=Hesitate-Barista8-Chewer
      - MATOMO_DATABASE_DBNAME=matomo
    depends_on:
      - db
    volumes:
      - app:/var/www/html

  db:
    image: mariadb:10.6
    container_name: matomo-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD=Hesitate-Barista8-Chewer
    volumes:
      - db:/var/lib/mysql


networks:
  default:
    external: true
    name: Apps-Network

volumes:
  app:
  db: 