services:
  ispyagentdvr:
    image: mekayelanik/ispyagentdvr:latest
    container_name: ispyAgentDVR
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - config:/AgentDVR/Media/XML
      - recordings:/AgentDVR/Media/WebServerRoot/Media
      - commands:/AgentDVR/Commands
    ports:
      - 8090:8090
      - 3478:3478/udp
      - 50000-50010:50000-50010/udp
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network

volumes:
  config:
  recordings:
  commands: