services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: MeTube
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - downloads:/downloads

networks:
  default:
    external: true
    name: Apps-Network

volumes:
  downloads: