---
version: "2.1"
services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - remmina:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

volumes:
  remmina:
    name: remmina
    external: true

networks:
  default:
    external:
      name: Apps-Network
