---
version: "2.1"
services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/appdata/remmina/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

networks:
  default:
#    external:
      name: Apps-Network
