services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx-Proxy-Manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/appdata/Nginx-Proxy/data:/data
      - /opt/appdata/Nginx-Proxy/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

networks:
  default:
    external: true
    name: Apps-Network
