version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx-Proxy-Manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - Nginx-Proxy:/data
      - Nginx-Proxy:/etc/letsencrypt
    restart: unless-stopped

volumes:
  Nginx-Proxy:
    name: Nginx-Proxy

networks:
  default:
    external:
      name: Apps-Network
